packages: []

allowBuilds: {}

blockExoticSubdeps: true

dangerouslyAllowAllBuilds: false

engineStrict: true

lockfile: true

minimumReleaseAge: 10080

minimumReleaseAgeIgnoreMissingTime: false

minimumReleaseAgeStrict: true

nodeVersion: 26.1.0

pmOnFail: error

preferFrozenLockfile: true

strictDepBuilds: true

strictStorePkgContentCheck: true

trustPolicy: no-downgrade

verifyDepsBeforeRun: error

verifyStoreIntegrity: true
