defmodule Mix.Tasks.Dev.Up do
  @shortdoc "Sets up worktree dev environment (env, services, db, caddy)"

  @moduledoc """
  Sets up a complete worktree development environment.

  1. Loads configuration from .env.local (or uses defaults)
  2. Verifies .env exists (copied by `wt step copy-ignored`)
  3. Starts Podman Compose services via local/compose.yml (Postgres, SeaweedFS S3, Chromium)
  4. Runs mix setup (ecto.create, ecto.migrate, assets)
  5. Registers Caddy route for `{branch}.firmowid.localhost`
  6. Starts Phoenix server in background

  ## Usage

      mix dev.up

  Configuration is read from .env.local (generated by worktrunk).
  If .env.local is missing, defaults are used (suitable for main branch).

  ## Prerequisites

  - .env file must exist (automatically copied by worktrunk via .worktreeinclude)
  - Caddy must be running with admin API on localhost/caddy
  - Podman must be available
  """

  use Mix.Task

  @defaults %{
    "PORT" => "4000",
    "DB_PORT" => "5433",
    "S3_PORT" => "4566",
    "CHROME_PORT" => "9222",
    "DEBUGGER_PORT" => "9229",
    "BRANCH" => "main",
    "DATABASE_URL" => "postgresql://postgres:postgres@localhost:5433/firmowid",
    "AWS_ACCESS_KEY_ID" => "test",
    "AWS_SECRET_ACCESS_KEY" => "test"
  }

  @impl Mix.Task
  def run(_args) do
    # Start applications needed for HTTP requests
    Application.ensure_all_started(:req)

    # Step 1: Load configuration from .env.local or use defaults
    env = load_env()

    branch = Map.fetch!(env, "BRANCH")
    port = Map.fetch!(env, "PORT")
    db_port = Map.fetch!(env, "DB_PORT")
    s3_port = Map.fetch!(env, "S3_PORT")
    chrome_port = Map.fetch!(env, "CHROME_PORT")
    debugger_port = Map.fetch!(env, "DEBUGGER_PORT")

    # Step 2: Verify .env exists (should be copied by `wt step copy-ignored`)
    verify_env_exists()

    # Step 3: Start Podman Compose services
    start_services(branch, port, db_port, s3_port, chrome_port)

    # Step 4: Run mix setup
    run_setup()

    # Step 4.5: Sync usage rules (AGENTS.md dependency rules)
    sync_usage_rules()

    # Step 5: Register Caddy route
    register_caddy_route(branch, port)

    # Step 6: Start Phoenix server in background
    start_phoenix_server()

    Mix.shell().info("")
    Mix.shell().info("Environment ready:")
    Mix.shell().info("  Phoenix:   http://#{sanitize_branch(branch)}.firmowid.localhost:8080 (or localhost:#{port})")
    Mix.shell().info("  Tidewave:  https://localhost:#{port}/tidewave/mcp")
    Mix.shell().info("  Postgres:  localhost:#{db_port}")
    Mix.shell().info("  S3:        localhost:#{s3_port}")
    Mix.shell().info("  Chromium:  localhost:#{chrome_port}")
    Mix.shell().info("  Debugger:  localhost:#{debugger_port}")
    Mix.shell().info("")
    Mix.shell().info("Logs: tail -f tmp/phoenix.log")
    Mix.shell().info("Stop: mix dev.down")
  end

  defp load_env do
    case File.read(".env.local") do
      {:ok, content} ->
        Mix.shell().info("Loading configuration from .env.local")
        parse_env(content)

      {:error, :enoent} ->
        Mix.shell().info("No .env.local found, using defaults (main branch setup)")
        generate_env_files(@defaults)
        @defaults
    end
  end

  defp parse_env(content) do
    content
    |> String.split("\n", trim: true)
    |> Enum.reject(&String.starts_with?(&1, "#"))
    |> Enum.reject(&(String.trim(&1) == ""))
    |> Map.new(fn line ->
      [key, value] = String.split(line, "=", parts: 2)
      {String.trim(key), String.trim(value)}
    end)
  end

  defp generate_env_files(env) do
    content = """
    PORT=#{env["PORT"]}
    DB_PORT=#{env["DB_PORT"]}
    S3_PORT=#{env["S3_PORT"]}
    CHROME_PORT=#{env["CHROME_PORT"]}
    DEBUGGER_PORT=#{env["DEBUGGER_PORT"]}
    BRANCH=#{env["BRANCH"]}
    DATABASE_URL=#{env["DATABASE_URL"]}

    # AWS credentials for SeaweedFS S3 (required by ex_aws)
    AWS_ACCESS_KEY_ID=#{env["AWS_ACCESS_KEY_ID"]}
    AWS_SECRET_ACCESS_KEY=#{env["AWS_SECRET_ACCESS_KEY"]}
    """

    File.write!(".env.local", content)
    Mix.shell().info("Generated .env.local with defaults")
  end

  defp verify_env_exists do
    if File.exists?(".env") do
      Mix.shell().info(".env found (copied by worktrunk)")
    else
      Mix.raise("""
      .env file not found!

      This file should be copied automatically by `wt step copy-ignored` during worktree creation.
      If you're setting up manually, copy .env from the main worktree first.
      """)
    end
  end

  defp start_services(branch, port, db_port, s3_port, chrome_port) do
    Mix.shell().info("Starting Podman Compose services...")

    compose_env = [
      {"COMPOSE_PROJECT_NAME", "firmowid-#{branch}"},
      {"PORT", to_string(port)},
      {"DB_PORT", to_string(db_port)},
      {"S3_PORT", to_string(s3_port)},
      {"CHROME_PORT", to_string(chrome_port)}
    ]

    compose_result =
      podman(["compose", "-f", "local/compose.yml", "up", "-d"], compose_env)

    case compose_result do
      {output, 0} ->
        Mix.shell().info(output)
        Mix.shell().info("Podman Compose services started")

      {output, code} ->
        Mix.shell().error("Podman Compose failed (exit #{code}):")
        Mix.shell().error(output)
        exit({:shutdown, code})
    end

    # Wait for postgres to be ready
    Mix.shell().info("Waiting for Postgres to be ready...")
    wait_for_postgres(db_port)
  end

  # Run podman via distrobox-host-exec if available (for distrobox containers),
  # otherwise try podman directly.
  # Env vars are passed inline since distrobox-host-exec doesn't forward them.
  defp podman(args, env) do
    env_prefix = Enum.map(env, fn {k, v} -> "#{k}=#{v}" end)

    cond do
      System.find_executable("distrobox-host-exec") ->
        # Use env command to set variables on the host side
        System.cmd("distrobox-host-exec", ["env" | env_prefix] ++ ["podman" | args], stderr_to_stdout: true)

      System.find_executable("podman") ->
        System.cmd("podman", args, env: env, stderr_to_stdout: true)

      System.find_executable("docker") ->
        System.cmd("docker", args, env: env, stderr_to_stdout: true)
    end
  end

  defp wait_for_postgres(port, attempts \\ 30) do
    case System.cmd("pg_isready", ["-h", "localhost", "-p", to_string(port)], stderr_to_stdout: true) do
      {_, 0} ->
        Mix.shell().info("Postgres is ready")

      {_, _} when attempts > 0 ->
        Process.sleep(1000)
        wait_for_postgres(port, attempts - 1)

      {output, _} ->
        Mix.raise("Postgres not ready after 30 seconds: #{output}")
    end
  end

  defp run_setup do
    Mix.shell().info("Running mix setup...")

    # Shell out to avoid Hex version conflicts when running in a fresh worktree
    case System.cmd("mix", ["setup"], stderr_to_stdout: true, into: IO.stream(:stdio, :line)) do
      {_, 0} ->
        Mix.shell().info("Setup complete")

      {_, code} ->
        Mix.raise("mix setup failed with exit code #{code}")
    end
  end

  defp sync_usage_rules do
    Mix.shell().info("Syncing usage rules into AGENTS.md...")

    case System.cmd("mix", ["usage_rules.sync", "--yes"], stderr_to_stdout: true) do
      {_, 0} ->
        Mix.shell().info("Usage rules synced")

      {output, _code} ->
        Mix.shell().error("Warning: usage_rules.sync failed (non-critical)")
        Mix.shell().error(output)
    end
  end

  defp start_phoenix_server do
    Mix.shell().info("Starting Phoenix server in background...")

    # Ensure tmp directory exists
    File.mkdir_p!("tmp")

    # Start Phoenix server in background, redirect output to log file
    pid_file = "tmp/phoenix.pid"
    log_file = "tmp/phoenix.log"

    # Use nohup + shell to properly background the process
    spawn(fn ->
      System.cmd(
        "sh",
        ["-c", "nohup mix phx.server > #{log_file} 2>&1 & echo $! > #{pid_file}"],
        stderr_to_stdout: true
      )
    end)

    # Give it a moment to start and write the PID
    Process.sleep(1000)

    case File.read(pid_file) do
      {:ok, pid} ->
        Mix.shell().info("Phoenix server started (PID: #{String.trim(pid)})")

      {:error, _} ->
        Mix.shell().info("Phoenix server starting... (check tmp/phoenix.log)")
    end
  end

  defp register_caddy_route(branch, port) do
    branch = sanitize_branch(branch)
    hostname = dev_hostname(branch)

    Mix.shell().info("Registering Caddy route for #{hostname}...")

    if System.user_home!() =~ "kosciak" do
      route_config = %{
        "id" => branch,
        "hostname" => hostname,
        "upstream" => "127.0.0.1:#{port}"
      }

      case Req.post("http://localhost:11190/api/routes", json: route_config) do
        {:ok, %{status: status}} when status in 200..299 ->
          Mix.shell().info("Caddy route registered: https://#{branch}.firmowid.localhost -> localhost:#{port}")

        {:ok, %{status: status, body: body}} ->
          Mix.shell().error("Warning: Failed to register Caddy route (status #{status})")
          Mix.shell().error(inspect(body))

        {:error, reason} ->
          Mix.shell().error("Warning: Failed to register Caddy route (is development-caddy running?)")
          Mix.shell().error(inspect(reason))
      end
    else
      admin_base_url = System.get_env("CADDY_ADMIN_URL") || "http://localhost:2019"

      case ensure_wt_server_exists(admin_base_url, branch, port) do
        :ok ->
          Mix.shell().info("Caddy route registered: http://#{hostname}:8080 -> localhost:#{port}")

        {:error, reason} ->
          Mix.shell().error("Warning: Failed to register Caddy route")
          Mix.shell().error(reason)
      end
    end
  end

  defp sanitize_branch(branch) do
    branch
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9-]/, "-")
    |> String.replace(~r/-+/, "-")
    |> String.trim("-")
    |> case do
      "" -> "main"
      sanitized -> sanitized
    end
  end

  defp dev_hostname(branch) do
    "#{branch}.firmowid.localhost"
  end

  defp ensure_wt_server_exists(admin_base_url, branch, port) do
    hostname = dev_hostname(branch)

    wt_server_config = %{
      "listen" => [":8080"],
      "automatic_https" => %{"disable" => true},
      "routes" => []
    }

    case Req.get(admin_base_url <> "/config/apps/http/servers/wt",
           connect_options: [timeout: 200],
           receive_timeout: 300
         ) do
      {:ok, %{status: 200, body: nil}} ->
        case Req.put(admin_base_url <> "/config/apps/http/servers/wt",
               json: wt_server_config,
               connect_options: [timeout: 200],
               receive_timeout: 1_000
             ) do
          {:ok, %{status: status}} when status in 200..299 ->
            :ok

          {:ok, %{status: status, body: body}} ->
            {:error, "Failed to create Caddy wt server (status #{status}): #{inspect(body)}"}

          {:error, reason} ->
            {:error, "Failed to create Caddy wt server: #{inspect(reason)}"}
        end

      {:ok, %{status: status}} when status in 200..299 ->
        :ok

      {:ok, %{status: status, body: body}} ->
        {:error, "Failed to read Caddy wt server (status #{status}): #{inspect(body)}"}

      {:error, reason} ->
        {:error, "Failed to read Caddy wt server: #{inspect(reason)}"}
    end

    _ = Req.delete("#{admin_base_url}/id/wt:firmowid:#{branch}")

    route_config = %{
      "@id" => "wt:firmowid:#{branch}",
      "match" => [%{"host" => [hostname]}],
      "handle" => [%{"handler" => "reverse_proxy", "upstreams" => [%{"dial" => "127.0.0.1:#{port}"}]}]
    }

    case Req.put("#{admin_base_url}/config/apps/http/servers/wt/routes/0",
           json: route_config,
           connect_options: [timeout: 200],
           receive_timeout: 1_000
         ) do
      {:ok, %{status: status}} when status in 200..299 ->
        :ok

      {:ok, %{status: status, body: body}} ->
        {:error, "Failed to register Caddy route (status #{status}): #{inspect(body)}"}

      {:error, reason} ->
        {:error, "Failed to register Caddy route: #{inspect(reason)}"}
    end
  end
end
