import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :firmowid, FirmowidWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: {:system, "PORT"}],
  url: [host: "new.firmowid.pl", port: 80],
  check_origin: ["https://new.firmowid.pl", "https://firmowid-redux.fly.dev"]

config :firmowid,
  uploads_bucket: "firmowid-uploads-prod"

config :sentry,
  dsn:
    "REMOVED_RETIRED_SENTRY_DSN",
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  integrations: [
    oban: [
      # Capture errors:
      capture_errors: true,
      # Monitor cron jobs:
      cron: [enabled: true]
    ]
  ]

config :ex_aws,
  access_key_id: "REMOVED_TIGRIS_ACCESS_KEY",
  secret_access_key: "REMOVED_TIGRIS_SECRET_KEY"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Firmowid.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
