import Config

# ErrorTracker configuration
config :error_tracker,
  repo: Firmowid.Repo,
  otp_app: :firmowid,
  enabled: true

config :firmowid, Firmowid.Currencies, rates_provider: :api

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :firmowid, FirmowidWeb.Core.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: {:system, "PORT"}],
  url: [host: "new.firmowid.pl", port: 80],
  check_origin: ["https://firmowid.pl", "https://*.d.alergeek.me"],
  force_ssl: [
    hsts: true,
    preload: true,
    subdomains: true,
    rewrite_on: [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto],
    exclude: ["localhost", "127.0.0.1"]
  ]

config :firmowid, :ksef,
  base_url: "https://api.ksef.mf.gov.pl/v2/",
  qr_code_base_url: "https://qr.ksef.mf.gov.pl"

# Do not print debug messages in production
config :logger, level: :info

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Disable Swoosh Local Memory Storage
config :swoosh, local: false
