import Config

config :firmowid, Firmowid.Currencies, rates_provider: :api

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :firmowid, FirmowidWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  http: [port: {:system, "PORT"}],
  url: [host: "new.firmowid.pl", port: 80],
  check_origin: ["https://new.firmowid.pl", "https://firmowid-redux.fly.dev"],
  force_ssl: [
    hsts: true,
    preload: true,
    subdomains: true,
    rewrite_on: [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]
  ]

config :firmowid,
  uploads_bucket: "firmowid-uploads-prod"

# Do not print debug messages in production
config :logger, level: :info

# Sentry configuration (DSN loaded from runtime.exs)
config :sentry,
  environment_name: Mix.env(),
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  integrations: [
    oban: [
      # Capture errors:
      capture_errors: true,
      # Monitor cron jobs:
      cron: [enabled: true]
    ]
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Disable Swoosh Local Memory Storage
config :swoosh, local: false
