defmodule Firmowid.Repo.Migrations.AddBillingFoundations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :billing_plan, :text, null: false, default: "przedsiebiorca"
    end

    execute("UPDATE organizations SET billing_plan = 'firma'")

    create table(:billing_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :month, :date, null: false
      add :billing_plan, :text, null: false, default: "przedsiebiorca"
      add :manual_external_invoices_count, :bigint, null: false, default: 0
      add :synced_bank_accounts_count, :bigint, null: false, default: 0
      add :active_non_owner_users_count, :bigint, null: false, default: 0
      add :frozen_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "billing_snapshots_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:billing_snapshots, [:organization_id, :month],
             name: "billing_snapshots_unique_month_per_organization_index"
           )
  end

  def down do
    drop constraint(:billing_snapshots, "billing_snapshots_organization_id_fkey")

    drop_if_exists unique_index(:billing_snapshots, [:organization_id, :month],
                     name: "billing_snapshots_unique_month_per_organization_index"
                   )

    drop table(:billing_snapshots)

    alter table(:organizations) do
      remove :billing_plan
    end
  end
end
