defmodule Firmowid.Repo.Migrations.AddMultitenancyToAshEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ash_events) do
      add :organization_id, :uuid, null: false
    end
  end

  def down do
    alter table(:ash_events) do
      remove :organization_id
    end
  end
end
