defmodule Firmowid.Repo.Migrations.AddUserEmploymentContract do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_employment_contracts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :worker_full_name, :text, null: false
      add :starts_at, :date, null: false
      add :salary, :money_with_currency, null: false

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_employment_contracts_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :blob_id,
          references(:blobs,
            column: :id,
            name: "user_employment_contracts_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "user_employment_contracts_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:user_employment_contracts, [:organization_id, :blob_id],
             name: "user_employment_contracts_unique_blob_index"
           )

    create unique_index(:user_employment_contracts, [:organization_id, :user_id, :starts_at],
             name: "user_employment_contracts_unique_contract_per_user_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :user_employment_contracts,
                     [:organization_id, :user_id, :starts_at],
                     name: "user_employment_contracts_unique_contract_per_user_org_index"
                   )

    drop_if_exists unique_index(:user_employment_contracts, [:organization_id, :blob_id],
                     name: "user_employment_contracts_unique_blob_index"
                   )

    drop constraint(:user_employment_contracts, "user_employment_contracts_organization_id_fkey")

    drop constraint(:user_employment_contracts, "user_employment_contracts_user_id_fkey")

    drop constraint(:user_employment_contracts, "user_employment_contracts_blob_id_fkey")

    drop table(:user_employment_contracts)
  end
end
