defmodule Firmowid.Repo.Migrations.AddUserSalaryEmploymentContractRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_salaries) do
      add :employment_contract_id,
          references(:user_employment_contracts,
            column: :id,
            name: "user_salaries_employment_contract_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    drop_if_exists index(:user_employment_contracts, [:organization_id, :blob_id],
                     name: "user_employment_contracts_unique_blob_index"
                   )

    create unique_index(:user_employment_contracts, [:organization_id, :blob_id],
             name: "user_employment_contracts_unique_blob_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_employment_contracts, [:organization_id, :blob_id],
                     name: "user_employment_contracts_unique_blob_index"
                   )

    create index(:user_employment_contracts, [:organization_id, :blob_id],
             name: "user_employment_contracts_unique_blob_index",
             unique: true
           )

    drop constraint(:user_salaries, "user_salaries_employment_contract_id_fkey")

    alter table(:user_salaries) do
      remove :employment_contract_id
    end
  end
end
