defmodule Firmowid.Repo.Migrations.RequireCostInvoiceMoney do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cost_invoices) do
      modify :amount, :money_with_currency, null: false
    end
  end

  def down do
    alter table(:cost_invoices) do
      modify :amount, :money_with_currency, null: true
    end
  end
end
