defmodule Firmowid.Repo.Migrations.AddDelegationTravelDetails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:delegations) do
      add :destination, :text, null: false
      add :transport_types, {:array, :text}, null: false
    end
  end

  def down do
    alter table(:delegations) do
      remove :transport_types
      remove :destination
    end
  end
end
