defmodule Firmowid.Repo.Migrations.MergeAddressFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :correspondence_address, :text
      add :residence_address, :text
    end

    execute """
    UPDATE users
    SET correspondence_address = NULLIF(TRIM(BOTH ', ' FROM
      CONCAT_WS(', ',
        NULLIF(correspondence_street, ''),
        NULLIF(TRIM(CONCAT_WS(' ', NULLIF(correspondence_code, ''), NULLIF(correspondence_city, ''))), '')
      )
    ), '')
    """

    execute """
    UPDATE users
    SET residence_address = NULLIF(TRIM(BOTH ', ' FROM
      CONCAT_WS(', ',
        NULLIF(residence_street, ''),
        NULLIF(TRIM(CONCAT_WS(' ', NULLIF(residence_code, ''), NULLIF(residence_city, ''))), '')
      )
    ), '')
    """

    alter table(:users) do
      remove :correspondence_street
      remove :correspondence_city
      remove :correspondence_code
      remove :residence_street
      remove :residence_city
      remove :residence_code
    end

    alter table(:leave_requests) do
      modify :category, :text, default: "absence"
    end

    # Legacy field superseded by the merged correspondence_address above.
    alter table(:organizations) do
      remove :correspondence_name
    end
  end

  def down do
    alter table(:organizations) do
      add :correspondence_name, :text
    end

    alter table(:leave_requests) do
      modify :category, :text, default: nil
    end

    alter table(:users) do
      add :residence_code, :text
      add :residence_city, :text
      add :residence_street, :text
      add :correspondence_code, :text
      add :correspondence_city, :text
      add :correspondence_street, :text
      remove :residence_address
      remove :correspondence_address
    end
  end
end
