defmodule Firmowid.Repo.Migrations.RetireCostInvoiceLegacyMoneyFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    :ok

    alter table(:cost_invoices) do
      remove :total_amount
      remove :currency
    end

    drop_if_exists constraint(:cost_invoices, :cost_invoices_amount_matches_legacy)
  end

  def down do
    alter table(:cost_invoices) do
      add :currency, :text
      add :total_amount, :decimal
    end

    distinct_currency_codes =
      repo().query!(~S|
  SELECT DISTINCT currency_code
  FROM (
    SELECT (amount).currency_code AS currency_code
    FROM cost_invoices
    WHERE amount IS NOT NULL
  ) currencies
  ORDER BY currency_code
  |).rows
      |> List.flatten()
      |> Enum.reject(&is_nil/1)

    invalid_currency_codes =
      Enum.reject(distinct_currency_codes, fn currency_code ->
        match?({:ok, _currency}, Money.validate_currency(currency_code))
      end)

    if invalid_currency_codes != [] do
      raise "Cost invoice money backfill failed because some historical currencies are invalid for ash_money: #{Enum.join(invalid_currency_codes, ", ")}. Normalize those rows first and rerun the migration."
    end

    execute(~S|
UPDATE cost_invoices
SET currency = (amount).currency_code,
    total_amount = (amount).amount
WHERE amount IS NOT NULL;
|)

    execute(~S|
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM cost_invoices
    WHERE (total_amount IS NULL) <> (currency IS NULL)
       OR total_amount IS NULL
  ) THEN
    RAISE EXCEPTION
      'Cost invoice money rollback failed: some rows have no legacy money values';
  END IF;
END
$$;
|)

    create constraint(:cost_invoices, :cost_invoices_amount_matches_legacy,
             check: """
               amount IS NULL OR ((amount).amount = total_amount AND (amount).currency_code = currency)
             """
           )

    create constraint(:cost_invoices, :cost_invoices_non_correction_total_amount_non_positive,
             check: """
               COALESCE((invoice_type)::text = ANY ((ARRAY['kor'::character varying, 'kor_zal'::character varying, 'kor_roz'::character varying])::text[]), false)
               OR total_amount <= (0)::numeric
             """
           )
  end
end
