defmodule Firmowid.Repo.Migrations.DelegationExpenses do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:delegation_expenses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :kind, :text, null: false
      add :original_filename, :text, null: false
      add :document_number, :text, null: false, default: ""
      add :expense_amount, :money_with_currency, null: false, default: fragment("('PLN', 0)")
      add :details, :map, null: false

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :delegation_id,
          references(:delegations,
            column: :id,
            name: "delegation_expenses_delegation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :blob_id,
          references(:blobs,
            column: :id,
            name: "delegation_expenses_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "delegation_expenses_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:delegation_expenses, "delegation_expenses_organization_id_fkey")

    drop constraint(:delegation_expenses, "delegation_expenses_blob_id_fkey")

    drop constraint(:delegation_expenses, "delegation_expenses_delegation_id_fkey")

    drop table(:delegation_expenses)
  end
end
