defmodule Firmowid.Repo.Migrations.DelegationSettlement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:delegation_expense_accommodation, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :original_filename, :text, null: false
      add :document_number, :text, null: false, default: ""
      add :expense_amount, :money_with_currency, null: false, default: fragment("('PLN', 0)")
      add :description, :text
      add :locality, :text, null: false, default: ""
      add :arrival_date, :date
      add :departure_date, :date

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :delegation_id,
          references(:delegations,
            column: :id,
            name: "delegation_expense_accommodation_delegation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "delegation_expense_accommodation_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:delegation_trip, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :departure_city, :text, null: false, default: ""
      add :departure_datetime, :utc_datetime, null: false
      add :arrival_city, :text, null: false, default: ""
      add :arrival_datetime, :utc_datetime, null: false
      add :description, :text

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :delegation_expense_transport_id, :uuid, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "delegation_trip_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:delegation_expense_transport, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:delegation_trip) do
      modify :delegation_expense_transport_id,
             references(:delegation_expense_transport,
               column: :id,
               name: "delegation_trip_delegation_expense_transport_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:delegation_expense_transport) do
      add :original_filename, :text, null: false
      add :document_number, :text, null: false, default: ""
      add :expense_amount, :money_with_currency, null: false, default: fragment("('PLN', 0)")
      add :transport_type, :text, null: false, default: "other"

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :delegation_id,
          references(:delegations,
            column: :id,
            name: "delegation_expense_transport_delegation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "delegation_expense_transport_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:delegation_expense_other, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :original_filename, :text, null: false
      add :document_number, :text, null: false, default: ""
      add :expense_amount, :money_with_currency, null: false, default: fragment("('PLN', 0)")
      add :description, :text, null: false, default: ""

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :delegation_id,
          references(:delegations,
            column: :id,
            name: "delegation_expense_other_delegation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "delegation_expense_other_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:delegation_expense_other, "delegation_expense_other_organization_id_fkey")

    drop constraint(:delegation_expense_other, "delegation_expense_other_delegation_id_fkey")

    drop table(:delegation_expense_other)

    drop constraint(
           :delegation_expense_transport,
           "delegation_expense_transport_organization_id_fkey"
         )

    drop constraint(
           :delegation_expense_transport,
           "delegation_expense_transport_delegation_id_fkey"
         )

    alter table(:delegation_expense_transport) do
      remove :organization_id
      remove :delegation_id
      remove :updated_at
      remove :inserted_at
      remove :transport_type
      remove :expense_amount
      remove :document_number
      remove :original_filename
    end

    drop constraint(:delegation_trip, "delegation_trip_organization_id_fkey")

    drop constraint(:delegation_trip, "delegation_trip_delegation_expense_transport_id_fkey")

    alter table(:delegation_trip) do
      modify :delegation_expense_transport_id, :uuid
    end

    drop table(:delegation_expense_transport)

    drop table(:delegation_trip)

    drop constraint(
           :delegation_expense_accommodation,
           "delegation_expense_accommodation_organization_id_fkey"
         )

    drop constraint(
           :delegation_expense_accommodation,
           "delegation_expense_accommodation_delegation_id_fkey"
         )

    drop table(:delegation_expense_accommodation)
  end
end
