defmodule Firmowid.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and then extended with a one-time conservative transaction cleanup.
  """

  use Ecto.Migration

  alias Firmowid.Ash.Finances.DuplicateTransactionMatcher

  require Logger

  # important! after we migrate this, migration can be a throwaway
  # (deduplication part)
  # that's why it's not worth it to inline it or do anything fancy

  @sandbox_institution_id "SANDBOXFINANCE_SFIN0000"

  @transaction_query """
  SELECT
    transactions.id,
    transactions.organization_id,
    transactions.bank_account_id,
    bank_accounts.institution_id,
    transactions.transaction_id,
    transactions.internal_transaction_id,
    transactions.creditor_name,
    transactions.creditor_account,
    transactions.debtor_name,
    transactions.debtor_account,
    transactions.transaction_amount,
    transactions.transaction_currency,
    transactions.booking_date,
    transactions.value_date,
    transactions.remittance_information_unstructured,
    transactions.inserted_at,
    transactions.updated_at
  FROM transactions
  INNER JOIN bank_accounts ON bank_accounts.id = transactions.bank_account_id
  WHERE transactions.bank_account_id IS NOT NULL
    AND COALESCE(bank_accounts.institution_id, '') != '#{@sandbox_institution_id}'
    AND COALESCE(transactions.booking_date, transactions.value_date) >= DATE '2026-01-01'
    AND COALESCE(transactions.booking_date, transactions.value_date) < DATE '2027-01-01'
  ORDER BY transactions.organization_id, transactions.bank_account_id, transactions.inserted_at ASC, transactions.id ASC
  """

  def up do
    cleanup_duplicate_like_transactions()

    drop_if_exists unique_index(:transactions, [:organization_id, :internal_transaction_id],
                     name: "transactions_unique_internal_tx_per_org_index"
                   )

    create unique_index(
             :transactions,
             [:organization_id, :internal_transaction_id, :bank_account_id],
             name: "transactions_unique_internal_tx_per_account_index"
           )
  end

  def down do
    raise "Irreversible migration: duplicate-like bank transactions were merged"
  end

  defp cleanup_duplicate_like_transactions do
    transactions =
      repo().query!(@transaction_query, [])
      |> rows_to_maps()

    {stats, _canonical_by_account} =
      Enum.reduce(transactions, {%{merged: 0, sales: 0, cost: 0, tags: 0}, %{}}, fn transaction,
                                                                                    {stats,
                                                                                     canonical_by_account} ->
        account_key = {transaction.organization_id, transaction.bank_account_id}
        canonical_transactions = Map.get(canonical_by_account, account_key, [])

        case DuplicateTransactionMatcher.matching_candidates(
               transaction,
               canonical_transactions,
               institution_id: transaction.institution_id
             ) do
          [] ->
            {stats,
             Map.update(canonical_by_account, account_key, [transaction], &[transaction | &1])}

          [canonical_transaction] ->
            updated_stats = merge_duplicate_transaction(transaction, canonical_transaction, stats)
            {updated_stats, canonical_by_account}

          ambiguous_candidates ->
            log_ambiguous_duplicate(transaction, ambiguous_candidates)

            {stats,
             Map.update(canonical_by_account, account_key, [transaction], &[transaction | &1])}
        end
      end)

    Logger.info(
      "Merged #{stats.merged} duplicate-like transactions; repointed #{stats.sales} sales joins, " <>
        "#{stats.cost} cost joins, #{stats.tags} transaction tags"
    )
  end

  defp merge_duplicate_transaction(duplicate_transaction, canonical_transaction, stats) do
    sales_repointed =
      repoint_invoice_links(
        "sales_invoices_transactions",
        "sales_invoice_id",
        duplicate_transaction,
        canonical_transaction
      )

    cost_repointed =
      repoint_invoice_links(
        "cost_invoices_transactions",
        "cost_invoice_id",
        duplicate_transaction,
        canonical_transaction
      )

    tag_repointed = repoint_transaction_tags(duplicate_transaction, canonical_transaction)

    repo().query!("DELETE FROM transactions WHERE id = $1", [duplicate_transaction.id])

    %{
      merged: stats.merged + 1,
      sales: stats.sales + sales_repointed,
      cost: stats.cost + cost_repointed,
      tags: stats.tags + tag_repointed
    }
  end

  defp log_ambiguous_duplicate(transaction, ambiguous_candidates) do
    candidate_ids = Enum.map(ambiguous_candidates, &format_value(&1.id))

    IO.puts(
      "AMBIGUOUS_DUPLICATE transaction_id=#{format_value(transaction.id)} internal_transaction_id=#{inspect(transaction.internal_transaction_id)} " <>
        "organization_id=#{format_value(transaction.organization_id)} bank_account_id=#{format_value(transaction.bank_account_id)} " <>
        "candidate_ids=#{inspect(candidate_ids)} remittance=#{inspect(transaction.remittance_information_unstructured)}"
    )
  end

  defp format_value(value) when is_binary(value) do
    case Ecto.UUID.cast(value) do
      {:ok, uuid} -> uuid
      :error -> inspect(value)
    end
  end

  defp format_value(value), do: inspect(value)

  defp repoint_invoice_links(table, invoice_column, duplicate_transaction, canonical_transaction) do
    update_sql = """
    UPDATE #{table} AS joined
    SET transaction_id = $1,
        updated_at = NOW()
    WHERE joined.transaction_id = $2
      AND NOT EXISTS (
        SELECT 1
        FROM #{table} AS existing
        WHERE existing.organization_id = joined.organization_id
          AND existing.#{invoice_column} = joined.#{invoice_column}
          AND existing.transaction_id = $1
      )
    """

    delete_sql = "DELETE FROM #{table} WHERE transaction_id = $1"

    %{num_rows: updated_rows} =
      repo().query!(update_sql, [canonical_transaction.id, duplicate_transaction.id])

    repo().query!(delete_sql, [duplicate_transaction.id])

    updated_rows
  end

  defp repoint_transaction_tags(duplicate_transaction, canonical_transaction) do
    insert_sql = """
    INSERT INTO transaction_entity_tags (
      id,
      kind,
      resource_id,
      tag_definition_id,
      organization_id,
      inserted_at,
      updated_at
    )
    SELECT
      uuid_generate_v7(),
      tags.kind,
      $1,
      tags.tag_definition_id,
      tags.organization_id,
      tags.inserted_at,
      NOW()
    FROM transaction_entity_tags AS tags
    WHERE tags.resource_id = $2
      AND NOT EXISTS (
        SELECT 1
        FROM transaction_entity_tags AS existing
        WHERE existing.resource_id = $1
          AND existing.organization_id = tags.organization_id
          AND (
            (tags.tag_definition_id IS NOT NULL AND existing.tag_definition_id = tags.tag_definition_id)
            OR (tags.tag_definition_id IS NULL AND existing.kind = tags.kind)
          )
      )
    """

    %{num_rows: inserted_rows} =
      repo().query!(insert_sql, [canonical_transaction.id, duplicate_transaction.id])

    repo().query!("DELETE FROM transaction_entity_tags WHERE resource_id = $1", [
      duplicate_transaction.id
    ])

    inserted_rows
  end

  defp rows_to_maps(%Postgrex.Result{columns: columns, rows: rows}) do
    Enum.map(rows, fn row ->
      columns
      |> Enum.zip(row)
      |> Map.new(fn {column, value} -> {String.to_existing_atom(column), value} end)
    end)
  end
end
