defmodule Firmowid.Repo.Migrations.RenameDelegationExpectedCostAndAddSignedCommand do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:delegations), :advance_payment_amount, to: :expected_cost

    alter table(:delegations) do
      add :advance_amount, :money_with_currency, null: false, default: fragment("('PLN', 0)")
      add :signed_command_filename, :text

      add :signed_command_blob_id,
          references(:blobs,
            column: :id,
            name: "delegations_signed_command_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:delegations, "delegations_signed_command_blob_id_fkey")

    alter table(:delegations) do
      remove :signed_command_blob_id
      remove :signed_command_filename
      remove :advance_amount
    end

    rename table(:delegations), :expected_cost, to: :advance_payment_amount
  end
end
