defmodule Firmowid.Repo.Migrations.CorrectUserSalaryDefaultStartsAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_salaries) do
      modify :starts_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:user_salaries) do
      modify :starts_at, :utc_datetime, default: fragment("CURRENT_DATE")
    end
  end
end
