defmodule Firmowid.Repo.Migrations.AddInvoiceNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_invoices) do
      add :invoice_note, :text
      add :internal_note, :text
    end
  end

  def down do
    alter table(:sales_invoices) do
      remove :internal_note
      remove :invoice_note
    end
  end
end
