defmodule Firmowid.Repo.Migrations.DropSlackId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :slack_id
    end
  end

  def down do
    alter table(:users) do
      add :slack_id, :text
    end
  end
end
