defmodule Firmowid.Repo.Migrations.Delegations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:delegations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :billing_month, :date, null: false
      add :purpose, :text, null: false
      add :advance_payment_amount, :money_with_currency, null: false
      add :start_date, :date, null: false
      add :end_date, :date, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "delegations_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "delegations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:leave_requests) do
      modify :category, :text, default: "absence"
    end
  end

  def down do
    alter table(:leave_requests) do
      modify :category, :text, default: nil
    end

    drop constraint(:delegations, "delegations_organization_id_fkey")

    drop constraint(:delegations, "delegations_user_id_fkey")

    drop table(:delegations)
  end
end
