defmodule Firmowid.Repo.Migrations.AddAnalysisAssignmentSource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_invoice_entity_tags) do
      add :assignment_source, :text, null: false, default: "manual"
    end

    alter table(:transaction_entity_tags) do
      add :assignment_source, :text, null: false, default: "manual"
    end

    alter table(:cost_invoice_entity_tags) do
      add :assignment_source, :text, null: false, default: "manual"
    end
  end

  def down do
    alter table(:cost_invoice_entity_tags) do
      remove :assignment_source
    end

    alter table(:transaction_entity_tags) do
      remove :assignment_source
    end

    alter table(:sales_invoice_entity_tags) do
      remove :assignment_source
    end
  end
end
