defmodule Firmowid.Repo.Migrations.AddVatExemptionFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :vat_exemption_type, :text
      add :vat_exemption_basis, :text
    end

    alter table(:sales_invoices) do
      add :vat_exemption_type, :text
      add :vat_exemption_basis, :text
    end
  end

  def down do
    alter table(:sales_invoices) do
      remove :vat_exemption_basis
      remove :vat_exemption_type
    end

    alter table(:organizations) do
      remove :vat_exemption_basis
      remove :vat_exemption_type
    end
  end
end
