defmodule Firmowid.Repo.Migrations.AddCounterpartyManagement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:counterparties) do
      add_if_not_exists :archived_at, :date
    end

    create_if_not_exists unique_index(:counterparties, [:organization_id, :pesel],
                           name: "counterparties_unique_pesel_per_org_index"
                         )

    create_if_not_exists unique_index(:counterparties, [:organization_id, :tax_id, :country],
                           name: "counterparties_unique_tax_id_country_per_org_index"
                         )
  end

  def down do
    drop_if_exists unique_index(:counterparties, [:organization_id, :tax_id, :country],
                     name: "counterparties_unique_tax_id_country_per_org_index"
                   )

    drop_if_exists unique_index(:counterparties, [:organization_id, :pesel],
                     name: "counterparties_unique_pesel_per_org_index"
                   )

    alter table(:counterparties) do
      remove :archived_at
    end
  end
end
