defmodule Firmowid.Repo.Migrations.HoursRecordChangeRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:hours_records) do
      add :change_request_kind, :text
      add :change_request_reason, :text
      add :change_requested_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:hours_records) do
      remove :change_requested_at
      remove :change_request_reason
      remove :change_request_kind
    end
  end
end
