defmodule Firmowid.Repo.Migrations.AddEmploymentContractState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_employment_contracts) do
      add :signed_at, :date
      add :contract_type, :text
      add :position, :text
      add :status, :text, null: false, default: "pending_signature"
      remove :worker_full_name
    end

    alter table(:users) do
      remove :position
    end
  end

  def down do
    alter table(:users) do
      add :position, :text
    end

    alter table(:user_employment_contracts) do
      add :worker_full_name, :text, null: false
      remove :status
      remove :position
      remove :contract_type
      remove :signed_at
    end
  end
end
