defmodule Firmowid.Repo.Migrations.AddOrganizationsParadedbSearchIdx do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX IF NOT EXISTS organizations_search_idx
    ON organizations
    USING bm25 (id, name, nip)
    WITH (key_field='id', text_fields='{
      "name": {"tokenizer": {"type": "ngram", "min_gram": 2, "max_gram": 4, "prefix_only": false}},
      "nip": {"tokenizer": {"type": "ngram", "min_gram": 2, "max_gram": 10, "prefix_only": true}}
    }');
    """)
  end

  def down do
    execute("""
    DROP INDEX IF EXISTS organizations_search_idx;
    """)
  end
end
