defmodule Firmowid.Repo.Migrations.NormalizeSessionBoundariesToMinutes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DO $$
    BEGIN
      ALTER TABLE sessions DISABLE TRIGGER no_session_overlap_trigger;

      UPDATE sessions
      SET
        start_datetime = date_trunc('minute', start_datetime),
        end_datetime = date_trunc('minute', end_datetime)
      WHERE
        start_datetime IS DISTINCT FROM date_trunc('minute', start_datetime)
        OR end_datetime IS DISTINCT FROM date_trunc('minute', end_datetime);

      ALTER TABLE sessions ENABLE TRIGGER no_session_overlap_trigger;
    END $$;
    """)
  end

  def down do
    execute("""
    SELECT 1;
    """)
  end
end
