defmodule Firmowid.Repo.Migrations.FixTransportTripTrigger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute(~S|CREATE OR REPLACE FUNCTION require_transport_expense_trip() RETURNS trigger AS $$
DECLARE
  transport_expense_id uuid;
BEGIN
  transport_expense_id := CASE
    WHEN TG_OP = 'INSERT' THEN (to_jsonb(NEW) ->> 'id')::uuid
    ELSE (to_jsonb(OLD) ->> 'delegation_expense_transport_id')::uuid
  END;

  IF EXISTS (SELECT 1 FROM delegation_expense_transport WHERE id = transport_expense_id)
     AND NOT EXISTS (
       SELECT 1 FROM delegation_trip
       WHERE delegation_expense_transport_id = transport_expense_id
     ) THEN
    RAISE EXCEPTION 'transport expense must contain at least one trip';
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;|)
  end

  def down do
    execute(~S|CREATE OR REPLACE FUNCTION require_transport_expense_trip() RETURNS trigger AS $$
DECLARE
  transport_expense_id uuid;
BEGIN
  transport_expense_id := CASE
    WHEN TG_TABLE_NAME = 'delegation_expense_transport' THEN NEW.id
    ELSE OLD.delegation_expense_transport_id
  END;

  IF EXISTS (SELECT 1 FROM delegation_expense_transport WHERE id = transport_expense_id)
     AND NOT EXISTS (
       SELECT 1 FROM delegation_trip
       WHERE delegation_expense_transport_id = transport_expense_id
     ) THEN
    RAISE EXCEPTION 'transport expense must contain at least one trip';
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;|)
  end
end
