defmodule Firmowid.Repo.Migrations.AddLeaveRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE EXTENSION IF NOT EXISTS \"btree_gist\"")

    create table(:leave_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :starts_on, :date, null: false
      add :ends_on, :date, null: false
      add :note, :text
      add :category, :text, null: false
      add :reason, :text, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "leave_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "leave_requests_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :blob_id,
          references(:blobs,
            column: :id,
            name: "leave_requests_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    execute("""
    ALTER TABLE leave_requests
    ADD CONSTRAINT no_overlapping_leave_requests
    EXCLUDE USING gist (
      user_id WITH =,
      daterange(starts_on, ends_on, '[]') WITH &&
    )
    WHERE (status IN ('accepted', 'pending'));
    """)
  end

  def down do
    execute("""
    ALTER TABLE leave_requests
    DROP CONSTRAINT no_overlapping_leave_requests;
    """)

    drop constraint(:leave_requests, "leave_requests_user_id_fkey")

    drop constraint(:leave_requests, "leave_requests_organization_id_fkey")

    drop constraint(:leave_requests, "leave_requests_blob_id_fkey")

    drop table(:leave_requests)
  end
end
