defmodule Firmowid.Repo.Migrations.AssistantSessionLifecycleRefactor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:assistant_sessions) do
      add :lock_version, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:assistant_sessions) do
      remove :lock_version
    end
  end
end
