defmodule Firmowid.Repo.Migrations.RequireCounterpartyCountry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "UPDATE counterparties SET country = 'PL' WHERE country IS NULL"

    alter table(:counterparties) do
      modify :country, :text, null: false
    end
  end

  def down do
    alter table(:counterparties) do
      modify :country, :text, null: true
    end
  end
end
