defmodule Firmowid.Repo.Migrations.RemoveDeprecatedSettingsFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :employment_contract_type
      remove :marketing_consent
      remove :student_status_until
    end

    alter table(:organizations) do
      remove :organization_type
      remove :phone_number
    end
  end

  def down do
    alter table(:organizations) do
      add :phone_number, :text
      add :organization_type, :text
    end

    alter table(:users) do
      add :student_status_until, :date
      add :marketing_consent, :boolean, null: false, default: false
      add :employment_contract_type, :text
    end
  end
end
