defmodule Firmowid.Repo.Migrations.AddSalesInvoiceEmailDelivery do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sales_invoices) do
      add :should_send_emails, :boolean, default: false
    end

    create table(:sales_invoice_email_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :delivery_type, :text, null: false
      add :status, :text, null: false
      add :recipient_email, :text
      add :resend_email_id, :text
      add :error_message, :text
      add :sent_at, :utc_datetime
      add :failed_at, :utc_datetime

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :sales_invoice_id,
          references(:sales_invoices,
            column: :id,
            name: "sales_invoice_email_deliveries_sales_invoice_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "sales_invoice_email_deliveries_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:sales_invoice_email_deliveries, [:organization_id, :sales_invoice_id])
  end

  def down do
    drop constraint(
           :sales_invoice_email_deliveries,
           "sales_invoice_email_deliveries_sales_invoice_id_fkey"
         )

    drop constraint(
           :sales_invoice_email_deliveries,
           "sales_invoice_email_deliveries_organization_id_fkey"
         )

    drop_if_exists index(:sales_invoice_email_deliveries, [:organization_id, :sales_invoice_id])

    drop table(:sales_invoice_email_deliveries)

    alter table(:sales_invoices) do
      remove :should_send_emails
    end
  end
end
