defmodule Firmowid.Repo.Migrations.RequireTransportExpenseTrip do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:delegation_trip) do
      modify :departure_datetime, :utc_datetime, null: true
      modify :arrival_datetime, :utc_datetime, null: true
    end

    drop constraint(:delegation_trip, "delegation_trip_delegation_expense_transport_id_fkey")

    alter table(:delegation_trip) do
      modify :delegation_expense_transport_id,
             references(:delegation_expense_transport,
               column: :id,
               name: "delegation_trip_delegation_expense_transport_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:delegation_expense_transport) do
      add :description, :text
    end

    execute(~S|CREATE FUNCTION require_transport_expense_trip() RETURNS trigger AS $$
DECLARE
  transport_expense_id uuid;
BEGIN
  transport_expense_id := CASE
    WHEN TG_TABLE_NAME = 'delegation_expense_transport' THEN NEW.id
    ELSE OLD.delegation_expense_transport_id
  END;

  IF EXISTS (SELECT 1 FROM delegation_expense_transport WHERE id = transport_expense_id)
     AND NOT EXISTS (
       SELECT 1 FROM delegation_trip
       WHERE delegation_expense_transport_id = transport_expense_id
     ) THEN
    RAISE EXCEPTION 'transport expense must contain at least one trip';
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;|)

    execute(~S|INSERT INTO delegation_trip (
  id,
  departure_city,
  arrival_city,
  delegation_expense_transport_id,
  organization_id,
  inserted_at,
  updated_at
)
SELECT
  uuid_generate_v7(),
  '',
  '',
  transport_expense.id,
  transport_expense.organization_id,
  NOW() AT TIME ZONE 'utc',
  NOW() AT TIME ZONE 'utc'
FROM delegation_expense_transport AS transport_expense
WHERE NOT EXISTS (
  SELECT 1
  FROM delegation_trip
  WHERE delegation_trip.delegation_expense_transport_id = transport_expense.id
);|)

    execute(~S|CREATE CONSTRAINT TRIGGER delegation_expense_transport_requires_trip
AFTER INSERT ON delegation_expense_transport
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION require_transport_expense_trip();|)

    execute(~S|CREATE CONSTRAINT TRIGGER delegation_trip_requires_transport_expense_sibling
AFTER DELETE ON delegation_trip
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION require_transport_expense_trip();|)
  end

  def down do
    execute("DROP TRIGGER delegation_trip_requires_transport_expense_sibling ON delegation_trip")

    execute(
      "DROP TRIGGER delegation_expense_transport_requires_trip ON delegation_expense_transport"
    )

    execute("DROP FUNCTION require_transport_expense_trip()")

    alter table(:delegation_expense_transport) do
      remove :description
    end

    drop constraint(:delegation_trip, "delegation_trip_delegation_expense_transport_id_fkey")

    alter table(:delegation_trip) do
      modify :delegation_expense_transport_id,
             references(:delegation_expense_transport,
               column: :id,
               name: "delegation_trip_delegation_expense_transport_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:delegation_trip) do
      modify :arrival_datetime, :utc_datetime, null: false
      modify :departure_datetime, :utc_datetime, null: false
    end
  end
end
