defmodule Firmowid.Repo.Migrations.AllowMultipleUnnumberedSalesInvoiceDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:sales_invoices, [:organization_id, :invoice_number],
                     name: "sales_invoices_invoice_number_per_org_index"
                   )

    create unique_index(:sales_invoices, [:organization_id, :invoice_number],
             name: "sales_invoices_invoice_number_per_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sales_invoices, [:organization_id, :invoice_number],
                     name: "sales_invoices_invoice_number_per_org_index"
                   )

    create unique_index(:sales_invoices, [:organization_id, :invoice_number],
             name: "sales_invoices_invoice_number_per_org_index",
             nulls_distinct: false
           )
  end
end
