defmodule Firmowid.Repo.Migrations.AddDelegationDetectedDates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:delegations) do
      add :detected_start_date, :date
      add :detected_end_date, :date
      add :date_change_reason, :text
    end
  end

  def down do
    alter table(:delegations) do
      remove :date_change_reason
      remove :detected_end_date
      remove :detected_start_date
    end
  end
end
