defmodule Firmowid.Repo.Migrations.CanonicalizeCounterpartyTaxId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:counterparties) do
      add :normalized_tax_id, :text
    end

    execute("""
    UPDATE counterparties
    SET normalized_tax_id = NULLIF(regexp_replace(upper(coalesce(tax_id, '')), '[^0-9A-Z]', '', 'g'), '')
    """)

    drop_if_exists unique_index(:counterparties, [:organization_id, :tax_id, :country],
                     name: "counterparties_unique_tax_id_country_per_org_index"
                   )

    create unique_index(:counterparties, [:organization_id, :normalized_tax_id, :country],
             name: "counterparties_unique_tax_id_country_per_org_index"
           )
  end

  def down do
    drop_if_exists unique_index(:counterparties, [:organization_id, :normalized_tax_id, :country],
                     name: "counterparties_unique_tax_id_country_per_org_index"
                   )

    create unique_index(:counterparties, [:organization_id, :tax_id, :country],
             name: "counterparties_unique_tax_id_country_per_org_index"
           )

    alter table(:counterparties) do
      remove :normalized_tax_id
    end
  end
end
