defmodule Firmowid.Repo.Migrations.ForeignCurrencyExpenseSettlement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:delegation_expenses) do
      add :settlement_method, :text
      add :settlement_amount, :money_with_currency
      add :nbp_rate, :decimal
      add :nbp_rate_date, :date

      add :statement_blob_id,
          references(:blobs,
            column: :id,
            name: "delegation_expenses_statement_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:delegation_expenses, "delegation_expenses_statement_blob_id_fkey")

    alter table(:delegation_expenses) do
      remove :statement_blob_id
      remove :nbp_rate_date
      remove :nbp_rate
      remove :settlement_amount
      remove :settlement_method
    end
  end
end
