defmodule Firmowid.Repo.Migrations.AddRoleToOrganizationInvite do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organization_invites) do
      add :role, :text, default: "employee"
    end
  end

  def down do
    alter table(:organization_invites) do
      remove :role
    end
  end
end
