defmodule Firmowid.Repo.Migrations.EnforceCostInvoiceMoneyInvariants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:cost_invoices, :cost_invoices_non_correction_amount_non_positive,
             check: """
               COALESCE((invoice_type)::text = ANY ((ARRAY['kor'::character varying, 'kor_zal'::character varying, 'kor_roz'::character varying])::text[]), false)
             OR (amount).amount <= (0)::numeric

             """
           )

    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM cost_invoices correction
        JOIN cost_invoices original
          ON original.ksef_number = correction.original_invoice_ksef_number
        WHERE correction.invoice_type IN ('kor', 'kor_zal', 'kor_roz')
          AND (correction.amount).currency_code IS DISTINCT FROM (original.amount).currency_code
      ) THEN
        RAISE EXCEPTION
          'Cost invoice money migration failed: linked corrections must use the original invoice currency';
      END IF;

    END
    $$;
    """)
  end

  def down do
    execute("""
    SELECT 1;
    """)

    drop_if_exists constraint(:cost_invoices, :cost_invoices_non_correction_amount_non_positive)
  end
end
