defmodule Firmowid.Repo.Migrations.RemoveKsefInvoiceDigestWindowsAndResetDigests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("DELETE FROM ksef_invoice_digest_items", "")
    execute("DELETE FROM ksef_invoice_digests", "")

    drop_if_exists unique_index(
                     :ksef_invoice_digests,
                     [:organization_id, :window_start, :window_end],
                     name: "ksef_invoice_digests_unique_window_index"
                   )

    alter table(:ksef_invoice_digests) do
      remove :window_end
      remove :window_start
    end
  end

  def down do
    create unique_index(:ksef_invoice_digests, [:organization_id, :window_start, :window_end],
             name: "ksef_invoice_digests_unique_window_index"
           )

    alter table(:ksef_invoice_digests) do
      add :window_start, :utc_datetime, null: false
      add :window_end, :utc_datetime, null: false
    end
  end
end
