defmodule Firmowid.Repo.Migrations.RequireTransactionDates do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      modify :value_date, :date, null: false
      modify :booking_date, :date, null: false
    end
  end

  def down do
    alter table(:transactions) do
      modify :booking_date, :date, null: true
      modify :value_date, :date, null: true
    end
  end
end
