defmodule Firmowid.Repo.Migrations.AddCurrentSessionIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:sessions, [:organization_id, :id, :user_id],
             name: "sessions_current_session_index"
           )
  end

  def down do
    drop_if_exists unique_index(:sessions, [:organization_id, :id, :user_id],
                     name: "sessions_current_session_index"
                   )
  end
end
