defmodule Firmowid.Repo.Migrations.MigrateResources1 do
  @moduledoc """
   Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  Duplicate-like transaction cleanup was already performed manually while
  preparing this branch, so the previous imperative deduplication code was
  intentionally removed from the migration.
  """

  use Ecto.Migration

  def up do
    # Duplicate-like transactions were already deduplicated before this migration
    # was finalized. We intentionally keep only the schema change here.

    drop_if_exists unique_index(:transactions, [:organization_id, :internal_transaction_id],
                     name: "transactions_unique_internal_tx_per_org_index"
                   )

    create unique_index(
             :transactions,
             [:organization_id, :internal_transaction_id, :bank_account_id],
             name: "transactions_unique_internal_tx_per_account_index"
           )
  end

  def down do
    raise "Irreversible migration: duplicate-like bank transactions were merged"
  end
end
