defmodule Firmowid.Repo.Migrations.AddDelegationReferenceCounters do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`.

  The trigger removal below is a one-time decommissioning step for the legacy
  reference allocator. AshPostgres has no trigger-removal DSL; new reference
  allocation is fully defined by `DelegationReferenceCounter` and
  `AssignReference`.
  """

  use Ecto.Migration

  def up do
    create table(:delegation_reference_counters, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :billing_month, :date, null: false
      add :initials, :text, null: false
      add :last_number, :bigint, null: false

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "delegation_reference_counters_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :delegation_reference_counters,
             [:organization_id, :billing_month, :initials],
             name: "delegation_reference_counters_unique_reference_namespace_index"
           )

    execute("DROP TRIGGER IF EXISTS assign_delegation_reference_before_insert ON delegations")
    execute("DROP FUNCTION IF EXISTS assign_delegation_reference()")
  end

  def down do
    drop constraint(
           :delegation_reference_counters,
           "delegation_reference_counters_organization_id_fkey"
         )

    drop_if_exists unique_index(
                     :delegation_reference_counters,
                     [:organization_id, :billing_month, :initials],
                     name: "delegation_reference_counters_unique_reference_namespace_index"
                   )

    drop table(:delegation_reference_counters)
  end
end
