defmodule Firmowid.Repo.Migrations.RelatedExpenseDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:delegation_expense_related_blobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :delegation_expense_id,
          references(:delegation_expenses,
            column: :id,
            name: "delegation_expense_related_blobs_delegation_expense_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :blob_id,
          references(:blobs,
            column: :id,
            name: "delegation_expense_related_blobs_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(
             :delegation_expense_related_blobs,
             [:organization_id, :delegation_expense_id, :blob_id],
             name: "delegation_expense_related_blobs_unique_expense_blob_index"
           )
  end

  def down do
    drop constraint(
           :delegation_expense_related_blobs,
           "delegation_expense_related_blobs_blob_id_fkey"
         )

    drop constraint(
           :delegation_expense_related_blobs,
           "delegation_expense_related_blobs_delegation_expense_id_fkey"
         )

    drop_if_exists unique_index(
                     :delegation_expense_related_blobs,
                     [:organization_id, :delegation_expense_id, :blob_id],
                     name: "delegation_expense_related_blobs_unique_expense_blob_index"
                   )

    drop table(:delegation_expense_related_blobs)
  end
end
