defmodule Firmowid.Repo.Migrations.PersistCostInvoiceAmountAsMoney do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cost_invoices) do
      add :amount, :money_with_currency
    end
  end

  def down do
    alter table(:cost_invoices) do
      remove :amount
    end
  end
end
