defmodule Firmowid.Repo.Migrations.ReviewHoursRecordChangeRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:hours_records, [:organization_id, :month, :year, :user_id],
                     name: "hours_records_unique_month_year_user_index"
                   )

    alter table(:hours_records) do
      add :submission_status, :text, null: false, default: "submitted"
      add :change_request_decision, :text
      add :change_reviewed_at, :utc_datetime_usec

      add :change_reviewer_id,
          references(:users,
            column: :id,
            name: "hours_records_change_reviewer_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:hours_records, [:organization_id, :month, :year, :user_id],
             name: "hours_records_unique_month_year_user_index",
             where: "(submission_status = 'submitted')"
           )
  end

  def down do
    drop constraint(:hours_records, "hours_records_change_reviewer_id_fkey")

    drop_if_exists unique_index(:hours_records, [:organization_id, :month, :year, :user_id],
                     name: "hours_records_unique_month_year_user_index"
                   )

    alter table(:hours_records) do
      remove :change_reviewer_id
      remove :change_reviewed_at
      remove :change_request_decision
      remove :submission_status
    end

    create unique_index(:hours_records, [:organization_id, :month, :year, :user_id],
             name: "hours_records_unique_month_year_user_index"
           )
  end
end
