defmodule Firmowid.Repo.Migrations.AddBirthdayVisibility do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :birthday_visibility, :text, null: false, default: "not_shared"
    end
  end

  def down do
    alter table(:users) do
      remove :birthday_visibility
    end
  end
end
