defmodule Firmowid.Repo.Migrations.NonNullBankAccountsForTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      modify :bank_account_id, :uuid, null: false
    end
  end

  def down do
    alter table(:transactions) do
      modify :bank_account_id, :uuid, null: true
    end
  end
end
