defmodule Firmowid.Repo.Migrations.AddDelegationReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:delegations) do
      add :reference, :text, null: false
    end

    create unique_index(:delegations, [:organization_id, :reference],
             name: "delegations_unique_reference_index"
           )
  end

  def down do
    drop_if_exists unique_index(:delegations, [:organization_id, :reference],
                     name: "delegations_unique_reference_index"
                   )

    alter table(:delegations) do
      remove :reference
    end
  end
end
