defmodule Firmowid.Repo.Migrations.DelegationExpenseBlobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:delegation_expense_accommodation) do
      add :blob_id,
          references(:blobs,
            column: :id,
            name: "delegation_expense_accommodation_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:delegation_expense_transport) do
      add :blob_id,
          references(:blobs,
            column: :id,
            name: "delegation_expense_transport_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:delegation_expense_other) do
      add :blob_id,
          references(:blobs,
            column: :id,
            name: "delegation_expense_other_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:delegation_expense_other, "delegation_expense_other_blob_id_fkey")

    alter table(:delegation_expense_other) do
      remove :blob_id
    end

    drop constraint(:delegation_expense_transport, "delegation_expense_transport_blob_id_fkey")

    alter table(:delegation_expense_transport) do
      remove :blob_id
    end

    drop constraint(
           :delegation_expense_accommodation,
           "delegation_expense_accommodation_blob_id_fkey"
         )

    alter table(:delegation_expense_accommodation) do
      remove :blob_id
    end
  end
end
