defmodule Firmowid.Repo.Migrations.AddKsefInvoiceDigests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ksef_invoice_digests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :window_start, :utc_datetime, null: false
      add :window_end, :utc_datetime, null: false
      add :delivered_at, :utc_datetime

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "ksef_invoice_digests_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:ksef_invoice_digests, [:organization_id, :window_start, :window_end],
             name: "ksef_invoice_digests_unique_window_index"
           )

    create table(:ksef_invoice_digest_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :digest_id,
          references(:ksef_invoice_digests,
            column: :id,
            name: "ksef_invoice_digest_items_digest_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :cost_invoice_id,
          references(:cost_invoices,
            column: :id,
            name: "ksef_invoice_digest_items_cost_invoice_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id, :uuid, null: false

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:ksef_invoice_digest_items, [:organization_id, :cost_invoice_id],
             name: "ksef_invoice_digest_items_unique_cost_invoice_index"
           )

    create unique_index(
             :ksef_invoice_digest_items,
             [:organization_id, :digest_id, :cost_invoice_id],
             name: "ksef_invoice_digest_items_unique_digest_invoice_pair_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :ksef_invoice_digest_items,
                     [:organization_id, :digest_id, :cost_invoice_id],
                     name: "ksef_invoice_digest_items_unique_digest_invoice_pair_index"
                   )

    drop_if_exists unique_index(:ksef_invoice_digest_items, [:organization_id, :cost_invoice_id],
                     name: "ksef_invoice_digest_items_unique_cost_invoice_index"
                   )

    drop constraint(:ksef_invoice_digest_items, "ksef_invoice_digest_items_digest_id_fkey")

    drop constraint(:ksef_invoice_digest_items, "ksef_invoice_digest_items_cost_invoice_id_fkey")

    drop table(:ksef_invoice_digest_items)

    drop_if_exists unique_index(
                     :ksef_invoice_digests,
                     [:organization_id, :window_start, :window_end],
                     name: "ksef_invoice_digests_unique_window_index"
                   )

    drop constraint(:ksef_invoice_digests, "ksef_invoice_digests_organization_id_fkey")

    drop table(:ksef_invoice_digests)
  end
end
