defmodule Firmowid.Repo.Migrations.RemoveRedundantDigestItemIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(
                     :ksef_invoice_digest_items,
                     [:organization_id, :digest_id, :cost_invoice_id],
                     name: "ksef_invoice_digest_items_unique_digest_invoice_pair_index"
                   )
  end

  def down do
    create unique_index(
             :ksef_invoice_digest_items,
             [:organization_id, :digest_id, :cost_invoice_id],
             name: "ksef_invoice_digest_items_unique_digest_invoice_pair_index"
           )
  end
end
