defmodule Firmowid.Repo.Migrations.BankAccountIdentityCurrency do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`

  The down migration restores the previous IBAN-only identity without deleting
  rows. It can fail when multi-currency rows share an organization and IBAN;
  those rows must be reconciled before rolling back.
  """

  use Ecto.Migration

  def up do
    execute("""
    DO $$
    DECLARE
      whitespace_chars text := concat(
        chr(9), chr(10), chr(11), chr(12), chr(13), chr(32), chr(133), chr(160),
        chr(5760), chr(8192), chr(8193), chr(8194), chr(8195), chr(8196), chr(8197),
        chr(8198), chr(8199), chr(8200), chr(8201), chr(8202), chr(8232), chr(8233),
        chr(8239), chr(8287), chr(12288)
      );
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM bank_accounts
        WHERE iban IS NULL
           OR translate(iban, whitespace_chars, '') = ''
      ) THEN
        RAISE EXCEPTION 'Cannot normalize bank account IBANs: a bank account has a missing or blank IBAN';
      END IF;

      IF EXISTS (
        SELECT 1
        FROM bank_accounts
        WHERE currency IS NULL
           OR btrim(currency, whitespace_chars) = ''
           OR btrim(currency, whitespace_chars) !~ '^[A-Za-z]{3}$'
      ) THEN
        RAISE EXCEPTION 'Cannot normalize bank account currencies: a bank account has a missing, blank, or invalid three-letter currency';
      END IF;

      IF EXISTS (
        SELECT 1
        FROM bank_accounts
        GROUP BY organization_id,
                 upper(translate(iban, whitespace_chars, '')),
                 upper(btrim(currency, whitespace_chars))
        HAVING count(*) > 1
      ) THEN
        RAISE EXCEPTION 'Cannot normalize bank accounts: canonicalization would create duplicate organization, IBAN, and currency groups';
      END IF;
    END;
    $$;
    """)

    drop_if_exists(
      unique_index(:bank_accounts, [:organization_id, :iban],
        name: "bank_accounts_unique_iban_per_org_index"
      )
    )

    execute("""
    WITH unicode_whitespace AS (
      SELECT concat(
        chr(9), chr(10), chr(11), chr(12), chr(13), chr(32), chr(133), chr(160),
        chr(5760), chr(8192), chr(8193), chr(8194), chr(8195), chr(8196), chr(8197),
        chr(8198), chr(8199), chr(8200), chr(8201), chr(8202), chr(8232), chr(8233),
        chr(8239), chr(8287), chr(12288)
      ) AS chars
    )
    UPDATE bank_accounts
    SET iban = upper(translate(bank_accounts.iban, unicode_whitespace.chars, '')),
        currency = upper(btrim(bank_accounts.currency, unicode_whitespace.chars))
    FROM unicode_whitespace
    """)

    create(
      unique_index(:bank_accounts, [:organization_id, :iban, :currency],
        name: "bank_accounts_unique_iban_currency_index"
      )
    )

    alter table(:bank_accounts) do
      modify(:currency, :text, null: false)
    end
  end

  def down do
    drop_if_exists(
      unique_index(:bank_accounts, [:organization_id, :iban, :currency],
        name: "bank_accounts_unique_iban_currency_index"
      )
    )

    create(
      unique_index(:bank_accounts, [:organization_id, :iban],
        name: "bank_accounts_unique_iban_per_org_index"
      )
    )

    alter table(:bank_accounts) do
      modify(:currency, :text, null: true)
    end
  end
end
