defmodule Firmowid.Repo.Migrations.AddAssistantSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:assistant_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :assistant_type, :text, null: false, default: "invoice_matching"
      add :status, :text, null: false, default: "active"
      add :title, :text
      add :system_prompt, :text, null: false
      add :entry_context, :map, null: false, default: %{}
      add :messages, {:array, :map}, null: false, default: []
      add :pending_match, :map
      add :last_error, :text

      add :inserted_at, :utc_datetime,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime, null: false, default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "assistant_sessions_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "assistant_sessions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:assistant_sessions, "assistant_sessions_organization_id_fkey")

    drop constraint(:assistant_sessions, "assistant_sessions_user_id_fkey")

    drop table(:assistant_sessions)
  end
end
