defmodule Firmowid.Repo.Migrations.UserSalaryStartsAddAndRemoveDeletedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_salaries) do
      remove :deleted_at
      add :starts_at, :utc_datetime, null: false, default: fragment("CURRENT_DATE")
    end

    drop_if_exists unique_index(:user_salaries, [:organization_id, :user_id],
                     name: "user_salaries_active_user_salary_index"
                   )

    create unique_index(:user_salaries, [:organization_id, :user_id, :starts_at],
             name: "user_salaries_unique_starts_at_per_user_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(:user_salaries, [:organization_id, :user_id, :starts_at],
                     name: "user_salaries_unique_starts_at_per_user_index"
                   )

    create unique_index(:user_salaries, [:organization_id, :user_id],
             name: "user_salaries_active_user_salary_index",
             nulls_distinct: false,
             where: "(deleted_at IS NULL)"
           )

    alter table(:user_salaries) do
      remove :starts_at
      add :deleted_at, :date
    end
  end
end
