defmodule Firmowid.Repo.Migrations.EnforceCostInvoiceMoneyInvariants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:cost_invoices, :cost_invoices_non_correction_amount_non_positive,
             check: """
               COALESCE((invoice_type)::text = ANY ((ARRAY['kor'::character varying, 'kor_zal'::character varying, 'kor_roz'::character varying])::text[]), false)
             OR (amount).amount <= (0)::numeric

             """
           )
  end

  def down do
    drop_if_exists constraint(:cost_invoices, :cost_invoices_non_correction_amount_non_positive)
  end
end
