defmodule Firmowid.Repo.Migrations.AddDelegationReferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:delegations) do
      add :reference, :text, null: false, default: ""
    end

    execute("""
    CREATE OR REPLACE FUNCTION assign_delegation_reference()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      initials text;
      sequence_number integer;
    BEGIN
      SELECT upper(string_agg(left(word, 1), ''))
      INTO initials
      FROM regexp_split_to_table(
        coalesce((SELECT name FROM public.users WHERE id = NEW.user_id), ''),
        E'\\s+'
      ) AS words(word)
      WHERE word <> '';

      initials := coalesce(
        nullif(initials, ''),
        'U' || upper(left((SELECT id::text FROM public.users WHERE id = NEW.user_id), 8))
      );

      PERFORM pg_advisory_xact_lock(
        hashtextextended(
          NEW.organization_id::text || ':' || NEW.user_id::text || ':' || to_char(NEW.billing_month, 'YYYY-MM'),
          0
        )
      );

      SELECT coalesce(max((regexp_match(reference, '-(\\d+)$'))[1]::integer), 0) + 1
      INTO sequence_number
      FROM delegations
      WHERE organization_id = NEW.organization_id
        AND user_id = NEW.user_id
        AND billing_month = NEW.billing_month;

      IF NEW.reference IS NULL OR NEW.reference = '' OR NEW.reference = 'pending' THEN
        NEW.reference := initials || '-' || to_char(NEW.billing_month, 'YYYY-MM') || '-' || sequence_number;
      END IF;
      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER assign_delegation_reference_before_insert
    BEFORE INSERT ON delegations
    FOR EACH ROW
    EXECUTE FUNCTION assign_delegation_reference();
    """)

    create unique_index(:delegations, [:organization_id, :reference],
             name: "delegations_unique_reference_index",
             where: "reference <> ''"
           )
  end

  def down do
    execute("DROP TRIGGER IF EXISTS assign_delegation_reference_before_insert ON delegations")
    execute("DROP FUNCTION IF EXISTS assign_delegation_reference()")

    drop_if_exists unique_index(:delegations, [:organization_id, :reference],
                     name: "delegations_unique_reference_index",
                     where: "reference <> ''"
                   )

    alter table(:delegations) do
      remove :reference
    end
  end
end
