defmodule Firmowid.Repo.Migrations.AddKsefCredentialLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  alias Firmowid.Ash.Ksef.Credential

  def up do
    alter table(:ksef_credentials) do
      modify :credentials, :binary, null: true
      add :status, :text, null: false, default: "authenticating"
      add :expires_on, :date
    end

    execute("""
    UPDATE ksef_credentials
    SET status = 'working'
    WHERE credentials IS NOT NULL
    """)

    flush()

    # The source certificate is application-encrypted, so its expiry must be
    # derived through the Ash resource after the generated columns are available.
    with_vault(fn ->
      Credential
      |> Ash.read!(authorize?: false)
      |> Enum.each(fn credential ->
        credential
        |> Ash.Changeset.for_update(:backfill_expiration_metadata, %{}, authorize?: false)
        |> Ash.update!(return_notifications?: true)
      end)
    end)
  end

  def down do
    alter table(:ksef_credentials) do
      remove :expires_on
      remove :status
      modify :credentials, :binary, null: false
    end
  end

  defp with_vault(fun) do
    case Process.whereis(Firmowid.Vault) do
      nil ->
        {:ok, vault} = Firmowid.Vault.start_link([])

        try do
          fun.()
        after
          GenServer.stop(vault)
        end

      _vault ->
        fun.()
    end
  end
end
