defmodule Firmowid.Ash.Blobs.Changes.UploadToS3 do
  @moduledoc """
  Preprocesses the uploaded file, computes a SHA-256 checksum, uploads to S3,
  and sets `blob_path`, `blob_checksum`, and `original_filename` on the changeset.

  Runs as a `before_action` hook so that S3 upload happens before the DB insert —
  if the upload fails, no orphaned record is created.

  Expects the changeset to carry three arguments:

    * `:upload_path` — local path to the file (temp file from Briefly or Phoenix)
    * `:content_type` — MIME type string
    * `:original_filename` — user-facing file name
  """
  use Ash.Resource.Change

  alias ExAws.S3

  @impl true
  def change(changeset, _opts, _context) do
    Ash.Changeset.before_action(changeset, fn changeset ->
      blob_id = Ash.Changeset.get_attribute(changeset, :id)

      upload_path = Ash.Changeset.get_argument(changeset, :upload_path)
      content_type = Ash.Changeset.get_argument(changeset, :content_type)
      original_filename = Ash.Changeset.get_argument(changeset, :original_filename)
      organization_id = changeset.tenant

      extension =
        content_type
        |> MIME.extensions()
        |> List.first("bin")

      upload_path = preprocess_file(Path.expand(upload_path), extension)
      blob_checksum = compute_checksum(upload_path)
      blob_path = "#{organization_id}/#{blob_id}.#{extension}"

      upload_to_s3!(upload_path, blob_path)

      changeset
      |> Ash.Changeset.force_change_attribute(:blob_path, blob_path)
      |> Ash.Changeset.force_change_attribute(:blob_checksum, blob_checksum)
      |> Ash.Changeset.force_change_attribute(:original_filename, original_filename)
    end)
  end

  # sobelow_skip ["Traversal.FileModule"]
  # upload_path comes from Briefly temp files or Phoenix uploads, not user input.
  defp compute_checksum(upload_path) do
    upload_path
    |> File.stream!()
    |> Enum.reduce(:crypto.hash_init(:sha256), &:crypto.hash_update(&2, &1))
    |> :crypto.hash_final()
    |> Base.encode16()
    |> String.downcase()
  end

  defp upload_to_s3!(upload_path, blob_path) do
    upload_path
    |> S3.Upload.stream_file()
    |> S3.upload(
      Application.get_env(:firmowid, :uploads_bucket),
      blob_path
    )
    |> ExAws.request!()
  end

  defp preprocess_file(path, extension) when extension in ["jpg", "jpeg", "png", "gif"] do
    shrink_image(path, extension)
  end

  defp preprocess_file(path, _extension), do: path

  # sobelow_skip ["Traversal.FileModule"]
  # path is generated by Briefly — OS-managed temp directory, not user input.
  defp shrink_image(image_path, image_extension) do
    with {:ok, path} <- Briefly.create() do
      image = Image.open!(image_path)
      width = Image.width(image)
      height = Image.height(image)

      scale =
        if width > height do
          min(1.0, 1000 / width)
        else
          min(1.0, 1000 / height)
        end

      resized_image =
        if scale < 1.0 do
          Image.resize!(image, scale)
        else
          image
        end

      binary_data =
        resized_image
        |> Image.stream!(suffix: ".#{image_extension}")
        |> Enum.to_list()
        |> IO.iodata_to_binary()

      File.write!(path, binary_data)

      path
    end
  end
end
