defmodule Firmowid.Ash.Invoicing.Services.PdfUtils do
  @moduledoc false

  alias Firmowid.Ash.Invoicing.Services.GotenbergClient

  @spec render_html_to_pdf(binary(), keyword()) :: {:ok, binary()} | {:error, term()}
  def render_html_to_pdf(html_content, opts \\ []) do
    GotenbergClient.convert_html(html_content, Keyword.put_new(opts, :scale, 1.25))
  end

  @doc """
  Transforms an XML document using an XSL stylesheet via `xsltproc`.

  Both arguments are binary strings (the file contents). Returns the
  transformed output (typically HTML) or an error tuple.
  """
  @spec xslt_transform(binary(), binary()) :: {:ok, binary()} | {:error, term()}
  # sobelow_skip ["Traversal.FileModule"]
  # These files are created in Briefly-managed temporary locations and are
  # never derived from user-controlled filesystem paths.
  def xslt_transform(xml_content, xsl_content) do
    xml_path = Briefly.create!(extname: ".xml")
    xsl_path = Briefly.create!(extname: ".xsl")

    File.write!(xml_path, xml_content)
    File.write!(xsl_path, xsl_content)

    case System.cmd("xsltproc", ["--nonet", xsl_path, xml_path], stderr_to_stdout: true) do
      {output, 0} -> {:ok, output}
      {output, status} -> {:error, {:xsltproc_failed, status, output}}
    end
  end

  @spec insert_page_after_first(binary(), binary()) :: {:ok, binary()} | {:error, term()}
  # sobelow_skip ["Traversal.FileModule"]
  # All paths are generated by Briefly and only used within this temp-file
  # workflow for qpdf post-processing.
  def insert_page_after_first(pdf_binary, inserted_page_binary) do
    source_path = Briefly.create!(extname: ".pdf")
    inserted_path = Briefly.create!(extname: ".pdf")
    output_path = Briefly.create!(extname: ".pdf")

    File.write!(source_path, pdf_binary)
    File.write!(inserted_path, inserted_page_binary)

    with {:ok, page_count} <- qpdf_page_count(source_path),
         {:ok, args} <- qpdf_insert_args(source_path, inserted_path, output_path, page_count) do
      case System.cmd("qpdf", args, stderr_to_stdout: true) do
        {_, 0} -> {:ok, File.read!(output_path)}
        {output, status} -> {:error, {:qpdf_failed, status, output}}
      end
    end
  end

  defp qpdf_page_count(path) do
    case System.cmd("qpdf", ["--show-npages", path], stderr_to_stdout: true) do
      {output, 0} ->
        case output |> String.trim() |> Integer.parse() do
          {page_count, ""} when page_count > 0 -> {:ok, page_count}
          _ -> {:error, {:qpdf_page_count_parse_failed, output}}
        end

      {output, status} ->
        {:error, {:qpdf_page_count_failed, status, output}}
    end
  end

  defp qpdf_insert_args(source_path, inserted_path, output_path, 1) do
    {:ok,
     [
       "--empty",
       "--pages",
       source_path,
       "1",
       inserted_path,
       "1",
       "--",
       output_path
     ]}
  end

  defp qpdf_insert_args(source_path, inserted_path, output_path, page_count) when page_count > 1 do
    {:ok,
     [
       "--empty",
       "--pages",
       source_path,
       "1",
       inserted_path,
       "1",
       source_path,
       "2-z",
       "--",
       output_path
     ]}
  end
end
