defmodule Firmowid.Ash.Invoicing.Services.SellerDisplayNameEnrichment do
  @moduledoc """
  Derives a seller display name for cost invoices from invoice contents.

  Historical cost invoices are used only as prompt context. The final display
  name is always generated by the LLM when a seller name is present.
  """

  alias Firmowid.Ash.Invoicing.CostInvoice
  alias OpenaiEx.Chat
  alias OpenaiEx.ChatMessage

  require Ash.Expr
  require Ash.Query
  require Logger

  @candidate_limit 20
  @max_history_scan 100
  @prompt_version 1

  @type candidate :: %{
          display_name: String.t(),
          seller: String.t() | nil,
          seller_nip: String.t() | nil
        }

  @spec generate_display_name(map(), keyword()) :: String.t() | nil
  def generate_display_name(document, opts \\ []) do
    seller = normalize_text(document[:seller] || document["seller"])
    seller_nip = normalize_tax_id(document[:seller_nip] || document["seller_nip"])
    items_list = normalize_items_list(document[:items_list] || document["items_list"])
    ash_opts = Keyword.get(opts, :ash_opts, [])
    current_cost_invoice_id = Keyword.get(opts, :current_cost_invoice_id)

    if is_nil(seller) do
      nil
    else
      historical_candidates =
        historical_candidates(seller, seller_nip, current_cost_invoice_id, ash_opts)

      seller
      |> generate_via_llm(seller_nip, items_list, historical_candidates)
      |> normalize_generated_display_name()
    end
  end

  @spec historical_candidates(String.t(), String.t() | nil, Ash.UUID.t() | nil, keyword()) ::
          [candidate()]
  defp historical_candidates(seller, seller_nip, current_cost_invoice_id, ash_opts) do
    current_cost_invoice_id
    |> historical_candidates_query(ash_opts)
    |> Ash.Query.filter(
      Ash.Expr.expr(
        (not is_nil(^seller_nip) and seller_nip == ^seller_nip) or
          contains(seller, ^seller) or
          contains(seller_display_name, ^seller)
      )
    )
    |> Ash.Query.sort(inserted_at: :desc, seller_display_name: :asc, seller: :asc, id: :desc)
    |> Ash.Query.limit(@max_history_scan)
    |> Ash.read!(ash_opts)
    |> unique_candidates()
    |> Enum.take(@candidate_limit)
  end

  @spec historical_candidates_query(Ash.UUID.t() | nil, keyword()) :: Ash.Query.t()
  defp historical_candidates_query(current_cost_invoice_id, ash_opts) do
    CostInvoice
    |> Ash.Query.for_read(:read, %{}, ash_opts)
    |> Ash.Query.select([:id, :seller, :seller_display_name, :seller_nip, :inserted_at])
    |> Ash.Query.filter(Ash.Expr.expr(not is_nil(seller_display_name) and seller_display_name != ""))
    |> maybe_exclude_current_invoice(current_cost_invoice_id)
  end

  defp maybe_exclude_current_invoice(query, nil), do: query

  defp maybe_exclude_current_invoice(query, current_cost_invoice_id) do
    Ash.Query.filter(query, Ash.Expr.expr(id != ^current_cost_invoice_id))
  end

  @spec unique_candidates([struct()]) :: [candidate()]
  defp unique_candidates(records) do
    {candidates, _seen} =
      Enum.reduce(records, {[], MapSet.new()}, fn record, {acc, seen} ->
        display_name = normalize_text(record.seller_display_name || record.seller)

        if is_nil(display_name) or MapSet.member?(seen, display_name) do
          {acc, seen}
        else
          candidate = %{
            display_name: display_name,
            seller: normalize_text(record.seller),
            seller_nip: normalize_tax_id(record.seller_nip)
          }

          {[candidate | acc], MapSet.put(seen, display_name)}
        end
      end)

    Enum.reverse(candidates)
  end

  @spec generate_via_llm(String.t(), String.t() | nil, [map()], [candidate()]) :: String.t() | nil
  defp generate_via_llm(seller, seller_nip, items_list, historical_candidates) do
    openai = :firmowid |> Application.get_env(:openai_api_key) |> OpenaiEx.new()

    request =
      Chat.Completions.new(
        model: "gpt-5-nano",
        temperature: 1,
        max_completion_tokens: 300,
        reasoning_effort: "minimal",
        messages: [
          %{
            role: "developer",
            content: developer_prompt()
          },
          seller
          |> user_prompt(seller_nip, items_list, historical_candidates)
          |> ChatMessage.user()
        ]
      )

    response = Chat.Completions.create!(openai, request)

    response["choices"]
    |> List.first()
    |> Map.get("message")
    |> Map.get("content")
  rescue
    error ->
      Logger.warning("Failed to generate seller display name via OpenAI: #{inspect(error)}")
      nil
  end

  defp developer_prompt do
    String.trim("""
    Jesteś asystentem księgowym. Tworzysz krótką, czytelną nazwę wyświetlaną sprzedawcy
    dla faktur kosztowych.

    Zasady:
    - Zwróć wyłącznie jedną nazwę, bez cudzysłowów i bez komentarza.
    - Historyczne nazwy traktuj wyłącznie jako sugestie i kontekst, nie jako obowiązkową odpowiedź.
    - Preferuj nazwy krótsze od pełnej nazwy prawnej, ale nadal jednoznaczne dla człowieka.
    - Usuń zbędne formy prawne, jeśli nie są potrzebne do identyfikacji.
    - Wygeneruj najlepszą krótką nazwę na podstawie bieżącej faktury i kontekstu historycznego.
    - Nie dodawaj informacji, których nie ma w danych wejściowych.

    Przykłady:
    - "STACJA PALIW PKN ORLEN NR 7333 ''BILMEX - TANK'' SPÓŁKA Z OGRANICZONĄ
      ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWA 30-348 KRAKÓW UL.GROTA ROWECKIEGO
      33 BDO00015385" -> "Stacja paliw Orlen w Krakowie"
      - franczyza, z perspektywy klienta to "Orlen", a nie "Bilmex"
      - miasto jest ważną informacją gdy mamy doczynienia z franczyzą
    - "LANTRE SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ" -> "Lantre"
      - prosta nazwa, bez zbędnych form prawnych
      - zawsze chcemy mieć słowa pisane wielką literą, nawet jeśli w danych
      wejściowych są małymi / całe wielkimi literami
    - "PGE POLSKA GRUPA ENERGETYCZNA SPÓŁKA AKCYJNA" -> "PGE"
      - akronim zawsze dużymi literami, ale znowu - bez zbędnych form prawnych
    - "VIKINGCO POLAND SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ" -> "VikingCo"
    """)
  end

  @spec user_prompt(String.t(), String.t() | nil, [map()], [candidate()]) :: String.t()
  defp user_prompt(seller, seller_nip, items_list, historical_candidates) do
    String.trim("""
    Wersja promptu: #{@prompt_version}

    Dane bieżącej faktury:
    - pełna nazwa sprzedawcy: #{seller}
    - NIP / tax id: #{seller_nip || "brak"}
    - pozycje faktury: #{inspect(Enum.take(items_list, 5))}

    Historyczne nazwy pasujące częściowo (maks. #{@candidate_limit}):
    #{format_candidates(historical_candidates)}

    Zwróć najlepszą jedną nazwę wyświetlaną sprzedawcy.
    """)
  end

  defp format_candidates([]), do: "- brak"

  defp format_candidates(candidates) do
    candidates
    |> Enum.with_index(1)
    |> Enum.map_join("\n", fn {candidate, index} ->
      "- #{index}. display_name=#{candidate.display_name}; seller=#{candidate.seller || "brak"}; seller_nip=#{candidate.seller_nip || "brak"}"
    end)
  end

  @spec normalize_generated_display_name(String.t() | nil) :: String.t() | nil
  defp normalize_generated_display_name(nil), do: nil

  defp normalize_generated_display_name(value) do
    case value |> to_string() |> String.trim() |> String.trim("\"'") do
      "" -> nil
      normalized -> normalized
    end
  end

  @spec normalize_text(String.t() | nil) :: String.t() | nil
  defp normalize_text(nil), do: nil

  defp normalize_text(value) do
    case value |> to_string() |> String.trim() do
      "" -> nil
      normalized -> normalized
    end
  end

  @spec normalize_tax_id(String.t() | nil) :: String.t() | nil
  defp normalize_tax_id(nil), do: nil

  defp normalize_tax_id(value) do
    value
    |> to_string()
    |> String.replace(~r/[^\p{N}A-Za-z]/u, "")
    |> String.upcase()
    |> case do
      "" -> nil
      normalized -> normalized
    end
  end

  defp normalize_items_list(items_list) when is_list(items_list), do: items_list
  defp normalize_items_list(_), do: []
end
