defmodule Firmowid.Ash.Blobs.UploadFingerprint do
  @moduledoc """
  Shared upload preprocessing and checksum logic for blobs.

  Ensures any code that needs to identify an uploaded file uses the same
  normalization steps as the blob creation pipeline.
  """

  @image_extensions ["jpg", "jpeg", "png", "gif"]

  @doc """
  Preprocesses a file the same way blob uploads do and returns its checksum.
  """
  @spec normalized_checksum(String.t(), String.t()) :: String.t()
  def normalized_checksum(upload_path, content_type) do
    upload_path
    |> Path.expand()
    |> preprocess_file(extension_for(content_type))
    |> compute_checksum()
  end

  @doc """
  Preprocesses a file for upload and returns the normalized path plus checksum.
  """
  @spec prepare_upload(String.t(), String.t()) :: {String.t(), String.t()}
  def prepare_upload(upload_path, content_type) do
    normalized_path = preprocess_file(Path.expand(upload_path), extension_for(content_type))
    {normalized_path, compute_checksum(normalized_path)}
  end

  defp extension_for(content_type) do
    content_type
    |> MIME.extensions()
    |> List.first("bin")
  end

  defp preprocess_file(path, extension) when extension in @image_extensions do
    shrink_image(path, extension)
  end

  defp preprocess_file(path, _extension), do: path

  # sobelow_skip ["Traversal.FileModule"]
  # upload_path comes from Briefly temp files or Phoenix uploads, not user input.
  defp compute_checksum(upload_path) do
    upload_path
    |> File.stream!()
    |> Enum.reduce(:crypto.hash_init(:sha256), &:crypto.hash_update(&2, &1))
    |> :crypto.hash_final()
    |> Base.encode16()
    |> String.downcase()
  end

  # sobelow_skip ["Traversal.FileModule"]
  # path is generated by Briefly — OS-managed temp directory, not user input.
  defp shrink_image(image_path, image_extension) do
    with {:ok, path} <- Briefly.create() do
      image = Image.open!(image_path)
      width = Image.width(image)
      height = Image.height(image)

      scale =
        if width > height do
          min(1.0, 1000 / width)
        else
          min(1.0, 1000 / height)
        end

      resized_image =
        if scale < 1.0 do
          Image.resize!(image, scale)
        else
          image
        end

      binary_data =
        resized_image
        |> Image.stream!(suffix: ".#{image_extension}")
        |> Enum.to_list()
        |> IO.iodata_to_binary()

      File.write!(path, binary_data)

      path
    end
  end
end
