name: Deploy production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: read

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: ghcr.io/alergeek-ventures/infrastructure/cicd-image:5b1d7150888c47322a6b5cda04796dfd1dbfb34c
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - name: Deploy to Coolify
        uses: Alergeek-Ventures/av-secret-service/coolify-deploy@17c852d6fda8206c131cc90ee8ba92f2b7133ef6
        with:
          infisical-identity-id: ${{ vars.INFISICAL_MACHINE_IDENTITY_ID }}
          infisical-project-slug: firmowid-z-hq-c
          coolify-token: ${{ secrets.COOLIFY_TOKEN }}
          coolify-app-uuid: ${{ vars.COOLIFY_APP_UUID }}
